In [ ]:
#!pip install xgboost

In [ ]:
#!pip install cython 
#dependency for rankeval

In [ ]:
#!pip install rankeval

In [ ]:
#!pip install optuna

In [11]:
import pandas as pd
import numpy as np
import os

In [12]:
from sklearn.model_selection import GroupShuffleSplit

In [13]:
from sklearn.metrics import ndcg_score, f1_score
from scipy.stats import spearmanr

In [14]:
import xgboost as xgb

In [15]:
import optuna

In [16]:
from sklearn.model_selection import GroupKFold

In [17]:
import joblib

In [ ]:
data = pd.read_csv("data/data.csv")

In [19]:
data.head()

,Driver,session_id,season,Avg_Lap_Time,Avg_Sector_1_Time,Avg_Sector_2_Time,Avg_Sector_3_Time,Avg_Speed,Max_Speed,Avg_Throttle,...,Team_Ferrari,Team_Haas F1 Team,Team_McLaren,Team_Mercedes,Team_Red Bull Racing,Team_Williams,Team_Racing Bulls,Team_Kick Sauber,Team_Alpine,Team_Aston Martin
0,44,2019_1,2019,99.887000,34.987722,26.688277,38.263285,72.362914,321.0,77.332428,...,False,False,False,True,False,False,False,False,False,False
1,77,2019_1,2019,102.112642,34.605052,26.578421,41.077666,77.224164,322.0,63.533740,...,False,False,False,True,False,False,False,False,False,False
2,5,2019_1,2019,102.006363,35.413562,26.630250,39.076916,64.468105,318.0,65.327970,...,True,False,False,False,False,False,False,False,False,False
3,33,2019_1,2019,99.378250,35.317647,27.301647,36.972250,68.294922,320.0,45.247477,...,False,False,False,False,True,False,False,False,False,False
4,16,2019_1,2019,98.392416,34.423823,26.681176,38.623153,68.324947,321.0,72.722550,...,True,False,False,False,False,False,False,False,False,False

In [ ]:
#splliting data for training and testing
#split is grouped by session_id
gss = GroupShuffleSplit(test_size=.30, n_splits=1, random_state = 11).split(data, groups=data['session_id'])

X_train_splits, X_test_splits = next(gss)

#Final_Race_Position is the target variable
train_data = data.iloc[X_train_splits]
X_train = train_data.loc[:, ~train_data.columns.isin(['session_id', 'Final_Race_Position'])]
y_train = train_data.loc[:, train_data.columns.isin(['Final_Race_Position'])]

test_data = data.iloc[X_test_splits]
X_test = test_data.loc[:, ~test_data.columns.isin(['session_id', 'Final_Race_Position'])]
y_test = test_data.loc[:, test_data.columns.isin(['Final_Race_Position'])]

In [22]:
X_train.shape

(1764, 30)

In [23]:
X_test.shape

(774, 30)

In [ ]:
#each qualifying session is a separate group
groups = train_data.groupby('session_id').size().to_numpy()
groups

array([20, 20, 19, 20, 19, 18, 20, 20, 20, 20, 18, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 19, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 19, 18, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 19, 19, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 19, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20])

In [25]:
model = xgb.XGBRanker(
    tree_method = 'hist', #fastest algorithm
    booster = 'gbtree', #gradient boosting
    objective = 'rank:pairwise', #comparing pairs of drivers
    random_state = 42,
    learning_rate = 0.1,
    colsample_bytree = 0.9, #percentage of features used
    max_depth = 6, #depth of trees
    n_estimators = 100, 
    subsample = 0.75,
    eval_metric = 'ndcg'
)

model.fit(X_train, y_train, group=groups, verbose=True)

XGBRanker(base_score=None, booster='gbtree', callbacks=None,
          colsample_bylevel=None, colsample_bynode=None, colsample_bytree=0.9,
          device=None, early_stopping_rounds=None, enable_categorical=False,
          eval_metric='ndcg', feature_types=None, feature_weights=None,
          gamma=None, grow_policy=None, importance_type=None,
          interaction_constraints=None, learning_rate=0.1, max_bin=None,
          max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=None,
          max_depth=6, max_leaves=None, min_child_weight=None, missing=nan,
          monotone_constraints=None, multi_strategy=None, n_estimators=100,
          n_jobs=None, num_parallel_tree=None, ...)

In [26]:
#predicting by each race
#the predict function does not take a group argument

def predict(model, df):
    scores = model.predict(df.drop(columns=['session_id', 'Final_Race_Position']))
    predictions_df = df.copy()
    predictions_df['predicted_score'] = scores
    predictions_df['predicted_position'] = predictions_df['predicted_score'].rank(ascending=True, method='first')
    return predictions_df

predictions = (
    test_data.groupby('session_id')
    .apply(lambda x: predict(model, x))
    .reset_index(drop=True)
)

In [27]:
predictions

,Driver,session_id,season,Avg_Lap_Time,Avg_Sector_1_Time,Avg_Sector_2_Time,Avg_Sector_3_Time,Avg_Speed,Max_Speed,Avg_Throttle,...,Team_McLaren,Team_Mercedes,Team_Red Bull Racing,Team_Williams,Team_Racing Bulls,Team_Kick Sauber,Team_Alpine,Team_Aston Martin,predicted_score,predicted_position
0,44,2019_1,2019,99.887000,34.987722,26.688277,38.263285,72.362914,321.0,77.332428,...,False,True,False,False,False,False,False,False,-1.479586,1.0
1,77,2019_1,2019,102.112642,34.605052,26.578421,41.077666,77.224164,322.0,63.533740,...,False,True,False,False,False,False,False,False,-1.153539,2.0
2,5,2019_1,2019,102.006363,35.413562,26.630250,39.076916,64.468105,318.0,65.327970,...,False,False,False,False,False,False,False,False,-0.414978,5.0
3,33,2019_1,2019,99.378250,35.317647,27.301647,36.972250,68.294922,320.0,45.247477,...,False,False,True,False,False,False,False,False,-0.688962,3.0
4,16,2019_1,2019,98.392416,34.423823,26.681176,38.623153,68.324947,321.0,72.722550,...,False,False,False,False,False,False,False,False,-0.520811,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769,2,2024_8,2024,86.852900,22.541250,39.724500,25.311800,31.497999,288.0,69.097964,...,False,False,False,True,False,False,False,False,0.571596,20.0
770,20,2024_8,2024,88.190000,25.223833,40.967666,28.480800,46.430601,294.0,67.484079,...,False,False,False,False,False,False,False,False,0.262595,18.0
771,11,2024_8,2024,88.602100,25.606333,39.694833,30.796272,31.072328,289.0,66.743170,...,False,False,True,False,False,False,False,False,0.061063,15.0
772,77,2024_8,2024,91.619666,24.757636,39.901818,26.462000,28.503915,289.0,70.254684,...,False,False,False,False,False,True,False,False,0.210623,16.0
773,24,2024_8,2024,89.128666,23.777454,40.314818,24.644444,28.447480,288.0,67.231715,...,False,False,False,False,False,True,False,False,0.340219,19.0

In [28]:
#precision@k

def top_k_precision(predictions, k):
    precision = []

    for _, group in predictions.groupby('session_id'):
        actual_top_k = set(group.nsmallest(k, 'Final_Race_Position')['Driver']) #actual ranks
        predicted_top_k = set(group.nsmallest(k, 'predicted_position')['Driver']) #predicted ranks

        correct_predictions = len(actual_top_k & predicted_top_k) #predicted drivers that were actually in the top k
        precision.append(correct_predictions / k)

    return np.mean(precision) #average precision across races

print("Winner Precision:", top_k_precision(predictions, k=1))
print("Top 3 Precision:", top_k_precision(predictions, k=3))
print("Top 10 Precision:", top_k_precision(predictions, k=10))

Winner Precision: 0.5128205128205128
Top 3 Precision: 0.6410256410256411
Top 10 Precision: 0.7666666666666667

In [29]:
#recall@k

def top_k_recall(predictions, k):
    recall = []

    for _, group in predictions.groupby('session_id'):
        actual_top_k = set(group.nsmallest(k, 'Final_Race_Position')['Driver']) #actual ranks
        predicted_top_k = set(group.nsmallest(k, 'predicted_position')['Driver']) #predicted ranks

        correct_predictions = len(actual_top_k & predicted_top_k)
        recall.append(correct_predictions / len(actual_top_k)) 

    return np.mean(recall) #average recall across races

print("Winner Recall:", top_k_recall(predictions, k=1))
print("Top 3 Recall:", top_k_recall(predictions, k=3))
print("Top 10 Recall:", top_k_recall(predictions, k=10))

Winner Recall: 0.5128205128205128
Top 3 Recall: 0.6410256410256411
Top 10 Recall: 0.7666666666666667

In [30]:
#F1@k

def top_k_f1(predictions, k):
    f1_scores = []

    for _, group in predictions.groupby('session_id'):
        actual_top_k = set(group.nsmallest(k, 'Final_Race_Position')['Driver']) #binary top k
        y_true = group['Driver'].apply(lambda x: 1 if x in actual_top_k else 0)

        predicted_top_k = set(group.nsmallest(k, 'predicted_position')['Driver']) #predicted binary top k
        y_pred = group['Driver'].apply(lambda x: 1 if x in predicted_top_k else 0)

        score = f1_score(y_true, y_pred)
        f1_scores.append(score)

    return np.mean(f1_scores)

print("Winner F1 Score:", top_k_f1(predictions, 1))
print("Top 3 F1 Score:", top_k_f1(predictions, 3))
print("Top 10 F1 Score:", top_k_f1(predictions, 10))

Winner F1 Score: 0.5128205128205128
Top 3 F1 Score: 0.6410256410256411
Top 10 F1 Score: 0.7666666666666667

In [31]:
#Spearman's Rank Correlation
#how well the predicted ranking order matches the true ranking order

def mean_spearman(df):
    scores = []
    for _, group in predictions.groupby('session_id'):
        true_ranks = group['Final_Race_Position']
        pred_ranks = group['predicted_position']

        corr, _ = spearmanr(true_ranks, pred_ranks)
        scores.append(corr)

    return np.mean(scores) #average across races

print("Mean Spearman's Rank Correlation:", mean_spearman(predictions))

Mean Spearman's Rank Correlation: 0.6131096973202237

In [32]:
#Normalized Discounted Cumulative Gain (NDCG)
#computes how well-ordered the rankings are

def compute_ndcg(group, k=10):
    group = group.copy()
    group['relevance'] = 1 / (group['Final_Race_Position'] + 1)

    y_true = group.sort_values('Final_Race_Position').head(k)['relevance'].values.reshape(1, -1)
    y_pred = group.sort_values('predicted_position').head(k)['relevance'].values.reshape(1, -1)

    return ndcg_score(y_true, y_pred)

ndcg_scores = predictions.groupby('session_id').apply(compute_ndcg, k=10)
print("Average NDCG for all Races:", ndcg_scores.mean())

Average NDCG for all Races: 0.9098258948150707

In [33]:
#Mean Reciprocal Rank (MRR)
#computes how early the model predicts the top rank - race winner

def compute_mrr(df):
    mrr_scores = []

    for session_id, group in df.groupby('session_id'):
        group_sorted = group.sort_values('predicted_position').reset_index(drop=True)

        #index of race winner
        winner_index = group_sorted[group_sorted['Final_Race_Position']==1].index

        if len(winner_index) > 0:
            #calculating reciprocal rank
            rr = 1.0 / (winner_index[0]+1) #adding 1 because it is a 0-based index
            mrr_scores.append(rr)

    return sum(mrr_scores)/len(mrr_scores) #average of reciprocal rank scores

mrr = compute_mrr(predictions)
print("Mean Reciprocal Rank:", mrr)

Mean Reciprocal Rank: 0.6727207977207977

In [ ]:
#hyperparameter tuning using Optuna

def objective(trial):
    param = {
        'tree_method': 'hist',
        'booster': 'gbtree',
        'objective': 'rank:pairwise',
        'eval_metric': 'ndcg',
        'random_state': 42,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0)
    }
    
    model = xgb.XGBRanker(**param)

    #cross-validation
    gkf = GroupKFold(n_splits=3) 
    scores = []
    
    session_ids = train_data['session_id'].values
    for train_idx, valid_idx in gkf.split(X_train, y_train, groups=session_ids):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[valid_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[valid_idx]
        session_tr = session_ids[train_idx]
        session_val = session_ids[valid_idx]

        group_tr = np.unique(session_tr, return_counts=True)[1]
        group_val = np.unique(session_val, return_counts=True)[1]

        model.fit(X_tr, y_tr, group=group_tr, verbose=False)

        preds = model.predict(X_val)
        
        ndcg = ndcg_score(y_val.values.reshape(1, -1), preds.reshape(1, -1))
        scores.append(ndcg)

    return np.mean(scores)

In [35]:
study = optuna.create_study(direction='maximize') #maximizing NDCG
study.optimize(objective, n_trials = 100)

[I 2025-04-29 14:18:21,693] A new study created in memory with name: no-name-8067a9c4-b766-4a00-b483-c728eada8eed
[I 2025-04-29 14:18:22,080] Trial 0 finished with value: 0.9505568996373971 and parameters: {'learning_rate': 0.03041872291022377, 'colsample_bytree': 0.7873526579170214, 'max_depth': 5, 'n_estimators': 467, 'subsample': 0.788188108556221}. Best is trial 0 with value: 0.9505568996373971.
[I 2025-04-29 14:18:22,279] Trial 1 finished with value: 0.9529853341788584 and parameters: {'learning_rate': 0.04029832156424745, 'colsample_bytree': 0.7688980348138582, 'max_depth': 8, 'n_estimators': 133, 'subsample': 0.8158421175757722}. Best is trial 1 with value: 0.9529853341788584.
[I 2025-04-29 14:18:22,427] Trial 2 finished with value: 0.9581362907658911 and parameters: {'learning_rate': 0.012283297897914158, 'colsample_bytree': 0.6579433169776243, 'max_depth': 7, 'n_estimators': 137, 'subsample': 0.7402857115037647}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:22,702] Trial 3 finished with value: 0.953007797791383 and parameters: {'learning_rate': 0.08207530025634203, 'colsample_bytree': 0.510311667687541, 'max_depth': 8, 'n_estimators': 215, 'subsample': 0.8324201338560007}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:23,085] Trial 4 finished with value: 0.9529472440523886 and parameters: {'learning_rate': 0.07511015362329967, 'colsample_bytree': 0.6256712681790384, 'max_depth': 7, 'n_estimators': 358, 'subsample': 0.849730815136506}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:23,238] Trial 5 finished with value: 0.9504501334705134 and parameters: {'learning_rate': 0.060044586882888384, 'colsample_bytree': 0.8881625319207709, 'max_depth': 3, 'n_estimators': 315, 'subsample': 0.670207940120187}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:23,537] Trial 6 finished with value: 0.9530852792868334 and parameters: {'learning_rate': 0.09699574148062064, 'colsample_bytree': 0.7938167277208897, 'max_depth': 9, 'n_estimators': 164, 'subsample': 0.8848083728874827}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:23,701] Trial 7 finished with value: 0.9513892771166939 and parameters: {'learning_rate': 0.03357371780592992, 'colsample_bytree': 0.8939181909391853, 'max_depth': 7, 'n_estimators': 134, 'subsample': 0.5605341224845758}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:23,788] Trial 8 finished with value: 0.9576711065839877 and parameters: {'learning_rate': 0.018635646915026432, 'colsample_bytree': 0.5222233759116663, 'max_depth': 4, 'n_estimators': 164, 'subsample': 0.5436261780281371}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:24,012] Trial 9 finished with value: 0.9548188038770394 and parameters: {'learning_rate': 0.014290447977212465, 'colsample_bytree': 0.5187838476995084, 'max_depth': 6, 'n_estimators': 314, 'subsample': 0.5133859185156494}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:24,489] Trial 10 finished with value: 0.9528728426573546 and parameters: {'learning_rate': 0.01089977764301536, 'colsample_bytree': 0.655960219760388, 'max_depth': 10, 'n_estimators': 222, 'subsample': 0.9911671295438595}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:24,620] Trial 11 finished with value: 0.9550332321729343 and parameters: {'learning_rate': 0.019333994908140358, 'colsample_bytree': 0.6239001921720186, 'max_depth': 4, 'n_estimators': 230, 'subsample': 0.6707899862629763}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:24,704] Trial 12 finished with value: 0.9524633731062445 and parameters: {'learning_rate': 0.019791981021723404, 'colsample_bytree': 0.6754718510576364, 'max_depth': 5, 'n_estimators': 102, 'subsample': 0.6492190611419111}. Best is trial 2 with value: 0.9581362907658911.
[I 2025-04-29 14:18:24,798] Trial 13 finished with value: 0.9597551201490394 and parameters: {'learning_rate': 0.01032397932042414, 'colsample_bytree': 0.5693973072302008, 'max_depth': 3, 'n_estimators': 189, 'subsample': 0.5804299592441685}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:25,009] Trial 14 finished with value: 0.9526176368529625 and parameters: {'learning_rate': 0.01019008991956236, 'colsample_bytree': 0.5899232396477633, 'max_depth': 6, 'n_estimators': 251, 'subsample': 0.7395790433883825}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:25,206] Trial 15 finished with value: 0.9571320775418584 and parameters: {'learning_rate': 0.014434106779528005, 'colsample_bytree': 0.9978478705447343, 'max_depth': 3, 'n_estimators': 384, 'subsample': 0.6042120118595614}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:25,462] Trial 16 finished with value: 0.9551533966267075 and parameters: {'learning_rate': 0.013859251837632834, 'colsample_bytree': 0.7064847301049173, 'max_depth': 8, 'n_estimators': 184, 'subsample': 0.7149006544326084}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:25,551] Trial 17 finished with value: 0.9540685761685266 and parameters: {'learning_rate': 0.024572509182573313, 'colsample_bytree': 0.5810663733172783, 'max_depth': 5, 'n_estimators': 104, 'subsample': 0.9430615965970263}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:26,047] Trial 18 finished with value: 0.9545954163155312 and parameters: {'learning_rate': 0.012134032161879737, 'colsample_bytree': 0.7120820537266539, 'max_depth': 10, 'n_estimators': 267, 'subsample': 0.6111542143841369}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:26,158] Trial 19 finished with value: 0.9515879631518103 and parameters: {'learning_rate': 0.051738374724216815, 'colsample_bytree': 0.5717420094208999, 'max_depth': 4, 'n_estimators': 193, 'subsample': 0.7679567684648538}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:26,607] Trial 20 finished with value: 0.9530742480424895 and parameters: {'learning_rate': 0.01626056216074989, 'colsample_bytree': 0.7306403236756895, 'max_depth': 6, 'n_estimators': 495, 'subsample': 0.7146261113449905}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:26,711] Trial 21 finished with value: 0.9578125257942176 and parameters: {'learning_rate': 0.01932465216839932, 'colsample_bytree': 0.5550226360356543, 'max_depth': 4, 'n_estimators': 160, 'subsample': 0.5214145014488536}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:26,789] Trial 22 finished with value: 0.9585328997930644 and parameters: {'learning_rate': 0.024541061985018323, 'colsample_bytree': 0.5640372552757882, 'max_depth': 3, 'n_estimators': 144, 'subsample': 0.5813045187859607}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:26,861] Trial 23 finished with value: 0.9577199700533526 and parameters: {'learning_rate': 0.025990254634984757, 'colsample_bytree': 0.6299354240739776, 'max_depth': 3, 'n_estimators': 131, 'subsample': 0.5888843669907061}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:26,991] Trial 24 finished with value: 0.9560002222442363 and parameters: {'learning_rate': 0.01197121530796597, 'colsample_bytree': 0.6627550332296579, 'max_depth': 3, 'n_estimators': 276, 'subsample': 0.633545803260935}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:27,181] Trial 25 finished with value: 0.9531668481367751 and parameters: {'learning_rate': 0.04006944583749621, 'colsample_bytree': 0.5563884691900991, 'max_depth': 7, 'n_estimators': 194, 'subsample': 0.5544186822888698}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:27,293] Trial 26 finished with value: 0.9563697086357501 and parameters: {'learning_rate': 0.010004858213289279, 'colsample_bytree': 0.5979672644465821, 'max_depth': 5, 'n_estimators': 146, 'subsample': 0.694219721019}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:27,466] Trial 27 finished with value: 0.9542098526064781 and parameters: {'learning_rate': 0.016151646398646333, 'colsample_bytree': 0.6852547218235384, 'max_depth': 9, 'n_estimators': 112, 'subsample': 0.5002609078041724}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:27,578] Trial 28 finished with value: 0.9556696465085629 and parameters: {'learning_rate': 0.02202885366568752, 'colsample_bytree': 0.5404145833631006, 'max_depth': 4, 'n_estimators': 194, 'subsample': 0.5852131361942823}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:27,910] Trial 29 finished with value: 0.952007356407957 and parameters: {'learning_rate': 0.030291464465471072, 'colsample_bytree': 0.8095431626734345, 'max_depth': 5, 'n_estimators': 437, 'subsample': 0.7954000022918283}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,025] Trial 30 finished with value: 0.9583248728510277 and parameters: {'learning_rate': 0.012061766001774048, 'colsample_bytree': 0.6152879150441988, 'max_depth': 3, 'n_estimators': 240, 'subsample': 0.8765162679657372}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,139] Trial 31 finished with value: 0.9567429726204626 and parameters: {'learning_rate': 0.013337777854621202, 'colsample_bytree': 0.6226431399858487, 'max_depth': 3, 'n_estimators': 234, 'subsample': 0.9213286777428804}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,229] Trial 32 finished with value: 0.95867049539958 and parameters: {'learning_rate': 0.01632815684680908, 'colsample_bytree': 0.600838464881689, 'max_depth': 3, 'n_estimators': 176, 'subsample': 0.7559546484273133}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,360] Trial 33 finished with value: 0.9570361705849111 and parameters: {'learning_rate': 0.016066720230939364, 'colsample_bytree': 0.5935725905269094, 'max_depth': 3, 'n_estimators': 284, 'subsample': 0.8688680940507487}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,472] Trial 34 finished with value: 0.9576515977433512 and parameters: {'learning_rate': 0.01143643388470935, 'colsample_bytree': 0.5046244166482337, 'max_depth': 4, 'n_estimators': 208, 'subsample': 0.8060448923845984}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,598] Trial 35 finished with value: 0.9559702180591878 and parameters: {'learning_rate': 0.02693450292835981, 'colsample_bytree': 0.7480752933191337, 'max_depth': 3, 'n_estimators': 249, 'subsample': 0.9009891586912614}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,702] Trial 36 finished with value: 0.954853177611111 and parameters: {'learning_rate': 0.02224172893136969, 'colsample_bytree': 0.5455547571392381, 'max_depth': 4, 'n_estimators': 174, 'subsample': 0.8359268352769326}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,862] Trial 37 finished with value: 0.9577631968397626 and parameters: {'learning_rate': 0.017303573448832144, 'colsample_bytree': 0.63735590355388, 'max_depth': 3, 'n_estimators': 349, 'subsample': 0.7703053821026745}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:28,941] Trial 38 finished with value: 0.956289133216278 and parameters: {'learning_rate': 0.013515095997687956, 'colsample_bytree': 0.6146836257929521, 'max_depth': 3, 'n_estimators': 147, 'subsample': 0.9498471835025927}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:29,061] Trial 39 finished with value: 0.9566166065165375 and parameters: {'learning_rate': 0.033182994906300806, 'colsample_bytree': 0.5381799706701643, 'max_depth': 4, 'n_estimators': 211, 'subsample': 0.6413179627558171}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:29,219] Trial 40 finished with value: 0.9541169832947346 and parameters: {'learning_rate': 0.021899042682276933, 'colsample_bytree': 0.5011209464586877, 'max_depth': 5, 'n_estimators': 250, 'subsample': 0.99545507297861}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:29,360] Trial 41 finished with value: 0.9559345354036672 and parameters: {'learning_rate': 0.011988989316891404, 'colsample_bytree': 0.5710222786002475, 'max_depth': 7, 'n_estimators': 123, 'subsample': 0.8567685710821488}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:29,563] Trial 42 finished with value: 0.9551678962531817 and parameters: {'learning_rate': 0.012714909002706616, 'colsample_bytree': 0.6510669603300195, 'max_depth': 8, 'n_estimators': 149, 'subsample': 0.734644071751972}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:29,654] Trial 43 finished with value: 0.956614671075116 and parameters: {'learning_rate': 0.01506281629025327, 'colsample_bytree': 0.6037456524048807, 'max_depth': 3, 'n_estimators': 177, 'subsample': 0.6745121381278665}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:29,816] Trial 44 finished with value: 0.9536370065107452 and parameters: {'learning_rate': 0.01045348963605171, 'colsample_bytree': 0.6844922405051139, 'max_depth': 7, 'n_estimators': 129, 'subsample': 0.8306080002263742}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:29,904] Trial 45 finished with value: 0.9578460944318149 and parameters: {'learning_rate': 0.011286646254725302, 'colsample_bytree': 0.6494417506129242, 'max_depth': 3, 'n_estimators': 169, 'subsample': 0.7690923615116564}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:30,097] Trial 46 finished with value: 0.9521303230027803 and parameters: {'learning_rate': 0.01773692690635533, 'colsample_bytree': 0.7783265617006493, 'max_depth': 6, 'n_estimators': 204, 'subsample': 0.5382839541989453}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:30,504] Trial 47 finished with value: 0.9529893919087415 and parameters: {'learning_rate': 0.014887018601057702, 'colsample_bytree': 0.527417148385069, 'max_depth': 9, 'n_estimators': 302, 'subsample': 0.6197132478159776}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:30,680] Trial 48 finished with value: 0.9577674603319745 and parameters: {'learning_rate': 0.01287601800739468, 'colsample_bytree': 0.5727181144922362, 'max_depth': 4, 'n_estimators': 237, 'subsample': 0.5807252464706648}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:30,786] Trial 49 finished with value: 0.9518973074704885 and parameters: {'learning_rate': 0.04615364895689172, 'colsample_bytree': 0.6049368343859926, 'max_depth': 4, 'n_estimators': 156, 'subsample': 0.6551680259174065}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,292] Trial 50 finished with value: 0.9530493170138433 and parameters: {'learning_rate': 0.03795677892132589, 'colsample_bytree': 0.8249536724711805, 'max_depth': 8, 'n_estimators': 224, 'subsample': 0.6884357355714458}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,385] Trial 51 finished with value: 0.9571218793227797 and parameters: {'learning_rate': 0.011206070986490206, 'colsample_bytree': 0.6455713255102127, 'max_depth': 3, 'n_estimators': 173, 'subsample': 0.767527167498921}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,455] Trial 52 finished with value: 0.959090505166634 and parameters: {'learning_rate': 0.011109251881236919, 'colsample_bytree': 0.6647116682340941, 'max_depth': 3, 'n_estimators': 115, 'subsample': 0.7169199350590383}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,529] Trial 53 finished with value: 0.9582912672204985 and parameters: {'learning_rate': 0.01013180348671154, 'colsample_bytree': 0.7066009149370092, 'max_depth': 3, 'n_estimators': 118, 'subsample': 0.7247337615963722}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,603] Trial 54 finished with value: 0.9577228589470996 and parameters: {'learning_rate': 0.010085978041395853, 'colsample_bytree': 0.7240862052225824, 'max_depth': 3, 'n_estimators': 116, 'subsample': 0.7303854456101111}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,684] Trial 55 finished with value: 0.9579258672575027 and parameters: {'learning_rate': 0.0125366432575667, 'colsample_bytree': 0.670364752542754, 'max_depth': 3, 'n_estimators': 139, 'subsample': 0.7094624418510617}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,772] Trial 56 finished with value: 0.957499142322897 and parameters: {'learning_rate': 0.011308416642023644, 'colsample_bytree': 0.9539885396842678, 'max_depth': 4, 'n_estimators': 105, 'subsample': 0.5692968117923723}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,847] Trial 57 finished with value: 0.9569687471469578 and parameters: {'learning_rate': 0.014708791589613584, 'colsample_bytree': 0.6906772880504364, 'max_depth': 3, 'n_estimators': 124, 'subsample': 0.7547147095741004}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:31,972] Trial 58 finished with value: 0.9564150387497298 and parameters: {'learning_rate': 0.013779625235974386, 'colsample_bytree': 0.7492136876886084, 'max_depth': 4, 'n_estimators': 188, 'subsample': 0.6217992286037467}. Best is trial 13 with value: 0.9597551201490394.
[I 2025-04-29 14:18:32,062] Trial 59 finished with value: 0.9604505887101453 and parameters: {'learning_rate': 0.010583375896735903, 'colsample_bytree': 0.7099012039474639, 'max_depth': 3, 'n_estimators': 155, 'subsample': 0.9622757804952629}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,154] Trial 60 finished with value: 0.9555807934333941 and parameters: {'learning_rate': 0.020278151375606845, 'colsample_bytree': 0.5631701714264589, 'max_depth': 3, 'n_estimators': 163, 'subsample': 0.9697224610744555}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,219] Trial 61 finished with value: 0.9585540136608387 and parameters: {'learning_rate': 0.010708922054651186, 'colsample_bytree': 0.7045241545654689, 'max_depth': 3, 'n_estimators': 101, 'subsample': 0.9013079829856098}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,283] Trial 62 finished with value: 0.957550192983923 and parameters: {'learning_rate': 0.010901213650400261, 'colsample_bytree': 0.5887045138348775, 'max_depth': 3, 'n_estimators': 101, 'subsample': 0.8996573090711903}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,382] Trial 63 finished with value: 0.9494575003009708 and parameters: {'learning_rate': 0.08058801534841888, 'colsample_bytree': 0.6226009133003667, 'max_depth': 4, 'n_estimators': 147, 'subsample': 0.9363136835867957}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,462] Trial 64 finished with value: 0.9591810246808574 and parameters: {'learning_rate': 0.011922238577263208, 'colsample_bytree': 0.7246314524418086, 'max_depth': 3, 'n_estimators': 139, 'subsample': 0.9787188009611586}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,555] Trial 65 finished with value: 0.9573296753926624 and parameters: {'learning_rate': 0.010860288086494073, 'colsample_bytree': 0.7384693454190827, 'max_depth': 4, 'n_estimators': 131, 'subsample': 0.9742292569281709}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,640] Trial 66 finished with value: 0.9590493955224099 and parameters: {'learning_rate': 0.015686849161304948, 'colsample_bytree': 0.7684774346556897, 'max_depth': 3, 'n_estimators': 135, 'subsample': 0.9743521815630665}. Best is trial 59 with value: 0.9604505887101453.
[I 2025-04-29 14:18:32,732] Trial 67 finished with value: 0.958940844704195 and parameters: {'learning_rate': 0.015530639206345297, 'colsample_bytree': 0.7673678130051504, 'max_depth': 3, 'n_estimators': 159, 'subsample': 0.9760613740732347}. Best is trial 59 with value: 0.9604505887101453.

In [36]:
trial = study.best_trial
print("Best Score:", trial.value) #best NDCG score
print("Best Params:")
for key, value in trial.params.items():
    print(key, ": ", value)

Best Score: 0.9604505887101453
Best Params:
learning_rate :  0.010583375896735903
colsample_bytree :  0.7099012039474639
max_depth :  3
n_estimators :  155
subsample :  0.9622757804952629

In [ ]:
#retrain model with optimal parameters

model = xgb.XGBRanker(
    tree_method = 'hist', #fastest algorithm
    booster = 'gbtree', #gradient boosting
    objective = 'rank:pairwise', #comparing pairs of drivers
    random_state = 42,
    learning_rate = 0.01,
    colsample_bytree = 0.71, #percentage of features used
    max_depth = 3, #depth of trees
    n_estimators = 155, 
    subsample = 0.962,
    eval_metric = 'ndcg'
)

model.fit(X_train, y_train, group=groups, verbose=True)

XGBRanker(base_score=None, booster='gbtree', callbacks=None,
          colsample_bylevel=None, colsample_bynode=None, colsample_bytree=0.71,
          device=None, early_stopping_rounds=None, enable_categorical=False,
          eval_metric='ndcg', feature_types=None, feature_weights=None,
          gamma=None, grow_policy=None, importance_type=None,
          interaction_constraints=None, learning_rate=0.01, max_bin=None,
          max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=None,
          max_depth=3, max_leaves=None, min_child_weight=None, missing=nan,
          monotone_constraints=None, multi_strategy=None, n_estimators=155,
          n_jobs=None, num_parallel_tree=None, ...)

In [38]:
def predict(model, df):
    scores = model.predict(df.drop(columns=['session_id', 'Final_Race_Position']))
    predictions_df = df.copy()
    predictions_df['predicted_score'] = scores
    predictions_df['predicted_position'] = predictions_df['predicted_score'].rank(ascending=True, method='first')
    return predictions_df

predictions2 = (
    test_data.groupby('session_id')
    .apply(lambda x: predict(model, x))
    .reset_index(drop=True)
)

In [39]:
print("-- Metrics with Optimal Parameters --")

print("Winner Precision:", top_k_precision(predictions2, k=1))
print("Top 3 Precision:", top_k_precision(predictions2, k=3))
print("Top 10 Precision:", top_k_precision(predictions2, k=10), "\n")

print("Winner Recall:", top_k_recall(predictions2, k=1))
print("Top 3 Recall:", top_k_recall(predictions2, k=3))
print("Top 10 Recall:", top_k_recall(predictions2, k=10), "\n")

print("Winner F1 Score:", top_k_f1(predictions2, 1))
print("Top 3 F1 Score:", top_k_f1(predictions2, 3))
print("Top 10 F1 Score:", top_k_f1(predictions2, 10), "\n")

print("Mean Spearman's Rank Correlation:", mean_spearman(predictions2), "\n")

ndcg_scores = predictions2.groupby('session_id').apply(compute_ndcg, k=10)
print("Average NDCG for all Races:", ndcg_scores.mean(), "\n")

print("Mean Reciprocal Rank:", compute_mrr(predictions2))

-- Metrics with Optimal Parameters --
Winner Precision: 0.5384615384615384
Top 3 Precision: 0.6752136752136753
Top 10 Precision: 0.7743589743589743

Winner Recall: 0.5384615384615384
Top 3 Recall: 0.6752136752136753
Top 10 Recall: 0.7743589743589743

Winner F1 Score: 0.5384615384615384
Top 3 F1 Score: 0.6752136752136753
Top 10 F1 Score: 0.7743589743589744

Mean Spearman's Rank Correlation: 0.6131096973202237

Average NDCG for all Races: 0.9217651743220173

Mean Reciprocal Rank: 0.7001942501942501

In [ ]:
#saving model
joblib.dump(model, 'f1_xgbranker.pkl')

['f1_xgbranker.pkl']

In [ ]:
#saving feature order
joblib.dump(X_train.columns.tolist(), 'train_columns.joblib')

['train_columns.joblib']